"""Clean-room bounded scaffolding and validation for small MCP servers."""

import ast
import json
import os
import re
import tomllib

from .document_ops import SkillExecutionError, _atomic_output, _receipt, _resolve_path


def _write_text(path, text):
    def write(temporary):
        with open(temporary, "w", encoding="utf-8") as stream:
            stream.write(text)

    _atomic_output(path, write)


def _python_files(project_name):
    return {
        "server.py": """from mcp.server.fastmcp import FastMCP\n\nmcp = FastMCP(%r)\n\n\n@mcp.tool()\ndef greet(name: str) -> str:\n    \"\"\"Return a small deterministic greeting.\"\"\"\n    return f\"Hello, {name}!\"\n\n\nif __name__ == \"__main__\":\n    mcp.run()\n""" % project_name,
        "pyproject.toml": """[build-system]\nrequires = [\"setuptools>=68\"]\nbuild-backend = \"setuptools.build_meta\"\n\n[project]\nname = %r\nversion = \"0.1.0\"\ndescription = \"Eva bounded MCP server scaffold\"\nrequires-python = \">=3.12\"\ndependencies = [\"mcp>=1.0,<3\"]\n""" % project_name,
        "README.md": "# %s\n\nGenerated by Eva's bounded MCP Builder. Install dependencies separately, then run `python server.py` over stdio.\n" % project_name,
    }


def _typescript_files(project_name):
    return {
        "src/index.ts": """import { McpServer } from \"@modelcontextprotocol/sdk/server/mcp.js\";\nimport { StdioServerTransport } from \"@modelcontextprotocol/sdk/server/stdio.js\";\n\nconst server = new McpServer({ name: %r, version: \"0.1.0\" });\nserver.tool(\"greet\", { name: { type: \"string\" } }, async ({ name }) => ({ content: [{ type: \"text\", text: `Hello, ${name}!` }] }));\nconst transport = new StdioServerTransport();\nawait server.connect(transport);\n""" % project_name,
        "package.json": __import__("json").dumps({
            "name": project_name,
            "version": "0.1.0",
            "private": True,
            "type": "module",
            "scripts": {"build": "tsc", "start": "node dist/index.js"},
            "dependencies": {"@modelcontextprotocol/sdk": "^1.0.0"},
            "devDependencies": {"typescript": "^5.0.0"},
        }, indent=2) + "\n",
        "README.md": "# %s\n\nGenerated by Eva's bounded MCP Builder. Install dependencies separately, then build and run over stdio.\n" % project_name,
    }


def _validate_python(project_path):
    source_path = os.path.join(project_path, "server.py")
    metadata_path = os.path.join(project_path, "pyproject.toml")
    if not os.path.isfile(source_path) or not os.path.isfile(metadata_path):
        raise SkillExecutionError("invalid_project", "Python MCP project must contain server.py and pyproject.toml.")
    with open(source_path, "r", encoding="utf-8") as stream:
        source = stream.read()
    ast.parse(source, filename=source_path)
    if "FastMCP" not in source or "@mcp.tool" not in source or "mcp.run()" not in source:
        raise SkillExecutionError("invalid_project", "Python MCP source is missing the expected bounded tool and stdio entry point.")
    with open(metadata_path, "r", encoding="utf-8") as stream:
        metadata = stream.read()
    try:
        parsed_metadata = tomllib.loads(metadata)
    except tomllib.TOMLDecodeError as exc:
        raise SkillExecutionError("invalid_project", "Python MCP metadata is not valid TOML.", {"message": str(exc)}) from exc
    project = parsed_metadata.get("project", {})
    dependencies = project.get("dependencies", [])
    if not isinstance(project, dict) or not project.get("name") or not project.get("requires-python") or not any(str(item).startswith("mcp") for item in dependencies):
        raise SkillExecutionError("invalid_project", "Python MCP metadata is missing project, dependency, or Python version declarations.")
    return {"status": "valid", "language": "python", "files": ["server.py", "pyproject.toml"]}


def _validate_typescript(project_path):
    source_path = os.path.join(project_path, "src", "index.ts")
    metadata_path = os.path.join(project_path, "package.json")
    if not os.path.isfile(source_path) or not os.path.isfile(metadata_path):
        raise SkillExecutionError("invalid_project", "TypeScript MCP project must contain src/index.ts and package.json.")
    with open(source_path, "r", encoding="utf-8") as stream:
        source = stream.read()
    with open(metadata_path, "r", encoding="utf-8") as stream:
        metadata = json.load(stream)
    required = ("McpServer", "StdioServerTransport", ".tool(", "connect(transport)")
    if any(marker not in source for marker in required):
        raise SkillExecutionError("invalid_project", "TypeScript MCP source is missing the expected tool and stdio transport declarations.")
    if not isinstance(metadata.get("scripts"), dict) or not metadata["scripts"].get("build") or "@modelcontextprotocol/sdk" not in metadata.get("dependencies", {}):
        raise SkillExecutionError("invalid_project", "TypeScript MCP metadata must declare a build script and SDK dependency.")
    return {"status": "valid", "language": "typescript", "files": ["src/index.ts", "package.json"]}


def execute_mcp_builder(request, roots):
    operation = str(request.get("operation") or "").strip().lower()
    if operation not in ("scaffold", "validate"):
        raise SkillExecutionError("unsupported_operation", "MCP Builder supports only scaffold and validate.", {"allowed": ["scaffold", "validate"]})
    root_name = str(request.get("root") or "artifacts").lower()
    project = request.get("output") if operation == "scaffold" else (request.get("input") or request.get("project"))
    project_path, display = _resolve_path(project, root_name, roots, kind="output" if operation == "scaffold" else "input", directory=True)
    options = request.get("options") or {}
    language = str(options.get("language") or "python").lower()
    if language not in ("python", "typescript"):
        raise SkillExecutionError("invalid_input", "MCP scaffold language must be python or typescript.")
    if not re.fullmatch(r"[a-z][a-z0-9_-]{1,47}", os.path.basename(project_path)):
        raise SkillExecutionError("invalid_input", "MCP project directory names must be lowercase and safe.")
    if operation == "scaffold":
        if os.path.isdir(project_path) and os.listdir(project_path):
            raise SkillExecutionError("output_exists", "Refusing to scaffold into a non-empty project directory.")
        os.makedirs(project_path, mode=0o700, exist_ok=True)
        files = _python_files(os.path.basename(project_path)) if language == "python" else _typescript_files(os.path.basename(project_path))
        for relative, content in files.items():
            target = os.path.join(project_path, relative)
            os.makedirs(os.path.dirname(target), mode=0o700, exist_ok=True)
            _write_text(target, content)
    validator = _validate_python if language == "python" else _validate_typescript
    validation = validator(project_path)
    return _receipt("mcp-builder", operation, [], display, validation, result={"language": language, "files": validation["files"], "message": "MCP project scaffold validated without installation or network access."})