name: Accessibility Test

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  accessibility:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Set up Node.js
        uses: actions/setup-node@v7
        with:
          node-version: "24"

      - name: Install pa11x Accessibility checker
        run: |
          npm install -g pa11y

      - name: Run Pa11y on local site
        run: |
          pa11y /home/runner/work/eva-agent/eva-agent/index.html --config .github/pa11y.json --reporter=cli --threshold 25
